	-- Disable foreign key checks temporarily
ALTER TABLE Post NOCHECK CONSTRAINT ALL;
ALTER TABLE AccountSnapshot NOCHECK CONSTRAINT ALL;
ALTER TABLE Hashtag NOCHECK CONSTRAINT ALL;
ALTER TABLE Reply NOCHECK CONSTRAINT ALL;
ALTER TABLE Comment NOCHECK CONSTRAINT ALL;
ALTER TABLE Topic NOCHECK CONSTRAINT ALL;
ALTER TABLE KeywordTopicWeight NOCHECK CONSTRAINT ALL;



-- Delete in dependency-safe order
DELETE FROM Hashtag;
DELETE FROM Post;
DELETE FROM AccountSnapshot;
DELETE FROM Account;
DELETE FROM Reply;
DELETE FROM Comment;
DELETE FROM Topic;
DELETE FROM KeywordTopicWeight;

-- Re-enable constraints
ALTER TABLE KeywordTopicWeight CHECK CONSTRAINT ALL;
ALTER TABLE Post CHECK CONSTRAINT ALL;
ALTER TABLE AccountSnapshot CHECK CONSTRAINT ALL;
ALTER TABLE Hashtag CHECK CONSTRAINT ALL;
ALTER TABLE Reply CHECK CONSTRAINT ALL;
ALTER TABLE Comment CHECK CONSTRAINT ALL;
ALTER TABLE Topic CHECK CONSTRAINT ALL;
